
// export type GroupCategory = 'Stokfella' | 'Micro-Loan' | 'Workers-Union';

// export type PaymentAccountType = 'MoMo' | 'BuildingSociety' | 'InstaCash' | 'Unayo' | 'Delta Pay' | 'Bank';

export const mockGroups = [
  {
    id: '1',
    name: 'Ezulwini Stokfellas',
    type: 'stokfellas',
    description: 'Community savings group for groceries and essentials',
    created_by: 'user1',
    admin_id: 'user1',
    total_members: 8,
    status: 'active',
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-11-06T08:30:00Z',
  },
  {
    id: '2',
    name: 'Mbabane Micro Loans',
    type: 'micro-loan',
    description: 'Small business loans for entrepreneurs',
    created_by: 'user2',
    admin_id: 'user2',
    total_members: 12,
    status: 'active',
    created_at: '2024-02-20T14:22:00Z',
    updated_at: '2024-11-05T09:15:00Z',
  },
  {
    id: '3',
    name: 'Teachers Union',
    type: 'workers-union',
    description: 'Teachers welfare and savings scheme',
    created_by: 'user3',
    admin_id: 'user3',
    total_members: 15,
    status: 'active',
    created_at: '2024-03-10T11:45:00Z',
    updated_at: '2024-11-04T16:20:00Z',
  },
];

export const mockTransactions = [
  {
    id: 't1',
    group_id: '1',
    user_id: 'currentUser',
    type: 'deposit',
    amount: 500,
    description: 'Monthly savings contribution',
    payment_method: 'MoMo',
    transaction_proof_url: '',
    status: 'completed',
    created_at: '2024-11-01T09:00:00Z',
    updated_at: '2024-11-01T09:05:00Z',
  },
  {
    id: 't2',
    group_id: '1',
    user_id: 'currentUser',
    type: 'withdrawal',
    amount: 1200,
    description: 'Grocery shopping round',
    payment_method: 'Bank',
    transaction_proof_url: '',
    status: 'completed',
    created_at: '2024-10-28T14:30:00Z',
    updated_at: '2024-10-28T14:35:00Z',
  },
  {
    id: 't3',
    group_id: '2',
    user_id: 'currentUser',
    type: 'loan',
    amount: 3000,
    description: 'Business startup capital',
    payment_method: 'Bank',
    transaction_proof_url: '',
    status: 'completed',
    created_at: '2024-10-15T10:15:00Z',
    updated_at: '2024-10-15T10:20:00Z',
  },
  {
    id: 't4',
    group_id: '1',
    user_id: 'currentUser',
    type: 'interest',
    amount: 75,
    description: 'Interest earned on savings',
    payment_method: 'Bank',
    transaction_proof_url: '',
    status: 'completed',
    created_at: '2024-10-30T08:00:00Z',
    updated_at: '2024-10-30T08:05:00Z',
  },
];

export const mockMemberAccounts = [
  {
    id: 'ma1',
    group_id: '1',
    user_id: 'currentUser',
    total_contributed: 2500,
    total_borrowed: 0,
    current_balance: 2575,
    interest_accumulated: 75,
    last_updated: '2024-11-06T08:00:00Z',
  },
  {
    id: 'ma2',
    group_id: '2',
    user_id: 'currentUser',
    total_contributed: 1500,
    total_borrowed: 3000,
    current_balance: -1500,
    interest_accumulated: 300,
    last_updated: '2024-11-06T08:00:00Z',
  },
  {
    id: 'ma3',
    group_id: '3',
    user_id: 'currentUser',
    total_contributed: 3000,
    total_borrowed: 0,
    current_balance: 3150,
    interest_accumulated: 150,
    last_updated: '2024-11-06T08:00:00Z',
  },
];

export const mockLoans = [
  {
    id: 'l1',
    group_id: '2',
    user_id: 'currentUser',
    amount_requested: 3000,
    amount_approved: 3000,
    interest_rate: 10,
    status: 'disbursed',
    requested_at: '2024-10-10T09:00:00Z',
    approved_at: '2024-10-12T10:30:00Z',
    due_date: '2024-11-15T23:59:59Z',
    repaid_at: null,
  },
  {
    id: 'l2',
    group_id: '2',
    user_id: 'currentUser',
    amount_requested: 2000,
    amount_approved: 0,
    interest_rate: 0,
    status: 'pending',
    requested_at: '2024-11-01T14:00:00Z',
    approved_at: null,
    due_date: null,
    repaid_at: null,
  },
];

export const mockGroupSettings = [
  {
    id: 'gs1',
    group_id: '1',
    payment_methods: ['MoMo', 'Bank', 'BuildingSociety'],
    subscription_frequency: 'monthly',
    subscription_amount: 500,
    interest_rate: 3,
    min_loan_amount: 1000,
    max_loan_amount: 50000,
    loan_term_days: 30,
  },
  {
    id: 'gs2',
    group_id: '2',
    payment_methods: ['Bank', 'MoMo', 'Unayo'],
    subscription_frequency: 'monthly',
    subscription_amount: 1000,
    interest_rate: 10,
    min_loan_amount: 2000,
    max_loan_amount: 100000,
    loan_term_days: 60,
  },
  {
    id: 'gs3',
    group_id: '3',
    payment_methods: ['Bank', 'DeltaPay'],
    subscription_frequency: 'monthly',
    subscription_amount: 800,
    interest_rate: 5,
    min_loan_amount: 1500,
    max_loan_amount: 75000,
    loan_term_days: 45,
  },
];
